name: NCTL Scan Dockerfile Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  GH_DEP_USERNAME: ${{secrets.GH_USERNAME}}
  GH_DEP_PAT: ${{secrets.GH_TOKEN}}

jobs:
  NCTL-Scan-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out additional repository code
        uses: actions/checkout@v4
        with:
          repository: nirmata/go-nctl
          ref: publish-report
          token: ${{ secrets.GH_TOKEN }} # Use the stored secret here
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - run: git config --global url.https://$GH_DEP_USERNAME:$GH_DEP_PAT@github.com/.insteadOf https://github.com/

      - name: Build go-nctl
        run: make linux

      - name: Check nctl version
        run: nctl version

      - name: NCTL Scan - Dockerfile
        run: nctl analyze git-repo --policies ./policy/ --publish --debug
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
